config:
  send_anonymous_usage_stats: false
  use_colors: true
  partial_parse: true
  printer_width: 4
  write_json: true
  warn_error: true


default:
  target: dev   # this is the default target
  outputs:
    dev:
      type: redshift
      host: localhost
      cluster_id: staging-master-dwh
      iam_profile: emnify-data-lake-staging-admin
      dbname: dw
      user: dbt
      method: iam
      port: 5439
      schema: test
      threads: 4
      keepalives_idle: 240  # default 240 seconds
      connect_timeout: 100  # default 10 seconds
      ra3_node: false
      retries: 3
    ci:
      type: redshift
      cluster_id: staging-master-dwh
      host: "10.190.21.193"
      dbname: dw
      user: dbt
      region: eu-west-1
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5439
      schema: test
      threads: 2
      keepalives_idle: 240  # default 240 seconds
      connect_timeout: 100  # default 10 seconds
      ra3_node: false
      retries: 3
    master_staging:
      type: redshift
      cluster_id: staging-master-dwh
      host: staging-master-dwh.c76carj9zaod.eu-west-1.redshift.amazonaws.com
      dbname: dw
      user: dbt
      region: eu-west-1
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5439
      schema: test
      threads: 2
      keepalives_idle: 240  # default 240 seconds
      connect_timeout: 100  # default 10 seconds
      ra3_node: false
      retries: 3
    emnify_prod:
      type: redshift
      method: iam
      iam_profile: emnify-data-lake-prod-data-engineer-default
      cluster_id: prod-emnify-dwh
      host: prod-emnify-dwh.c6ytqnuwvrwk.eu-west-1.redshift.amazonaws.com
      region: eu-west-1
      dbname: dw
      user: dbt
      port: 5439
      schema: public
      autocommit: True
      threads: 2
      connect_timeout: 1800 # default 10 seconds
      sslmode: prefer
      ra3_node: false
      retries: 3
    1nce_prod:
      type: redshift
      method: iam
      iam_profile: emnify-data-lake-prod-data-engineer-default
      cluster_id: prod-1nce-dwh
      host: prod-1nce-dwh.clvgarq5n8vj.eu-central-1.redshift.amazonaws.com
      region: eu-central-1
      dbname: dw
      user: dbt
      port: 5439
      schema: public
      autocommit: True
      threads: 2
      connect_timeout: 1800 # default 10 seconds
      sslmode: prefer
      ra3_node: false
      retries: 3
